name: Sheduler Saham
on: 
  schedule:
    - cron : '0 17 * * 1-5'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Run The App
        run: node index.js ${{ secrets.USER }} ${{ secrets.PASS }} ${{ secrets.EMAIL }} ${{ secrets.SYMBOL }}   
